---
params:
  sizeCut: 130
  includeDMEK: TRUE
  includeDSAEK: TRUE
  includeUT_DSAEK: TRUE
  
header-includes:
  - \newcommand\latexcode[1]{#1}
  
title: "PCA for UDD paper"
author: "Alexis Derumigny"
date: "`r Sys.Date()`"

output: 
  bookdown::word_document2:
    toc: true
    fig_caption: true

knit: |
  (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', Sys.Date(), '.docx'
      ),
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

# Loading packages
library(readxl)
library(tidyverse)
library(ggforce)
library(ade4)
library(adegraphics)

# Loading cleaning functions
myFolder = "D:/applicationsNum/22 - Greffe cornee UT DSAEK/"
source(paste0(myFolder,"Graft_cornea_code/functions_cleaning.R"))
```

# Introduction

## Inclusion in the dataset

```{r, results="asis", warning=FALSE, label="loading data"}
folder = paste0(myFolder, "data/")
nameFile = "COMPARAISON DMEK DSAEK UT DSAEK jmp09092022 2023-01-17.xlsx"

# nomTableaux = c("dmek", "dsaek", "ut_dsaek")

vecNumbersSheets =  c()
nomTableaux = c()

cat("Category | State\n")
cat("---------|------\n")

if (params$includeDMEK){
  vecNumbersSheets = c(vecNumbersSheets, 1)
  nomTableaux = c(nomTableaux, "dmek")
  cat("DMEK | included\n")
}
if (params$includeDSAEK){
  vecNumbersSheets = c(vecNumbersSheets, 2)
  nomTableaux = c(nomTableaux, "dsaek")
  cat("DSAEK | included\n")
} else {
  cat("DSAEK | not included\n")
}
if (params$includeUT_DSAEK){
  vecNumbersSheets = c(vecNumbersSheets, 3)
  if (params$sizeCut == 130){
    nomTableaux = c(nomTableaux, "ut_dsaek")
    cat("UT DSAEK | included with cut at $130 µm$\n")
  } else if (params$sizeCut == 160){
    nomTableaux = c(nomTableaux, "ut_dsaek")
    cat("UT DSAEK | included with cut at $160 µm$\n")
  }
} else{
  cat("UT DSAEK | not included\n")
}

stopifnot(length(nomTableaux) == length(vecNumbersSheets))

listeTableaux = list()
for (iTableau in 1:length(nomTableaux))
{
  listeTableaux[[iTableau]] <- 
    data.frame(read_xlsx(
      path = paste0(folder, nameFile),
      sheet = paste0("Feuil", vecNumbersSheets[iTableau]),
      col_types = "numeric"))
  
  listeTableaux[[iTableau]]$method <- nomTableaux[iTableau]
}
```


## Different normalizations

```{r, results="asis", warning=FALSE, label="choices normalizations"}
df_normalizations = tribble(
  ~PACHY, ~BSCVA, ~ECD,
  FALSE, FALSE, FALSE,
  TRUE , FALSE, FALSE,
  FALSE, TRUE , FALSE,
  TRUE , TRUE , FALSE,
  
  TRUE , TRUE , TRUE,
  TRUE , FALSE, TRUE,
  FALSE, FALSE, TRUE,
  FALSE, TRUE , TRUE
)

df_normalizations = df_normalizations %>%
  mutate(across(.fns = function (x){if_else(x, "Normalized", "Un-normalized")},
                .names = "{.col}_norm"))
cat("PACHY | BSCVA (Visual acuities) | ECD (Endothelial Cell.densities) | Section\n")
# cat(" |  |  | -\n")
cat("----------|----------|----------|-----------\n")
for (i in 1:nrow(df_normalizations)){
  cat(paste(df_normalizations$PACHY_norm[i],
            df_normalizations$BSCVA_norm[i],
            df_normalizations$ECD_norm[i], sep = " | "))
  cat(" | ")
  cat(paste("\\@ref(s:", paste(substring(df_normalizations$PACHY_norm[i], 1, 1),
                               substring(df_normalizations$BSCVA_norm[i], 1, 1),
                               substring(df_normalizations$ECD_norm[i], 1, 1),sep = "-"),
            ")", sep = ""))
  cat("\n")
}
```


## Variables list and description

```{r, results="asis", warning=FALSE, label="renaming variables"}

# to get the full variable list
#
# sort(unique(unlist(lapply(listeTableaux, colnames))))

catCategory("General characteristics:")

listeTableaux = listeTableaux %>%
  updateColnames("woman","WOMAN") %>%
  updateColnames("man","MAN") %>%
  updateColnames("patient.age", "age") %>%
  updateColnames("right.eye", "RIGHT.EYE") %>%
  updateColnames("left.eye", "LEFT.EYE") %>%
  updateColnames("second.graft", "SECOND.GRAFT")

catCategory("Characteristics of the surgery:")

listeTableaux = listeTableaux %>%
  updateColnames("locoregional.anaesthesia", "loco.regional.anaesthesia") %>%
  updateColnames("general.anaesthesia") %>%
  updateColnames("surgery.duration", 
                 c("surgical.procedure.duration..mn.",
                   "PROCEDURE..duration..mn.")) %>%
  updateColnames("cutting.blade.gradient")

catCategory("Characteristics of the graft:")  

listeTableaux = listeTableaux %>%
  updateColnames("graft.age","graft.s.age") %>%
  updateColnames("rebbubling", 
                 c("graft.detachment.episode",
                   "GRAFT.DETACHMENT.EPISOD") ) %>%
  updateColnames("multiple.rebbubling", 
                 c("multiple.graft.detachment.episod")) %>%
  updateColnames("graft.rejection",  
                 c("graft..rejection.episod") ) %>%
  updateColnames("Stromal_marking",
                 c("STROMAL.MARKING.OF.THE.GRAFT"), "for DMEK graft") %>%
  updateColnames("failure", c("failure of transplant to restore quantifiable visual acuity",
                              "echec", "graft.failure", "dsaek.failure")) %>%
  updateColnames("failure.primary", "primary.graft.failure") %>%
  updateColnames("success", "dsaek.success")
  
  
catCategory("History of the graft:")  

listeTableaux = listeTableaux %>%
  updateColnames("1st DMEK", "primo.DMEK",
                 paste("signifie que c'est la première greffe de type dmek",
                       "réalisée, sans qu'aucune autre greffe de type dmek",
                       "ou dsaek n'ait été réalisée au préalable") ) %>%
  updateColnames("1st DSAEK", "primo.DSAEK") %>%
  mergingColnames("second.graft",
                  c("DMEK.post.dmek", "DSAEKpost.dmek", "DSAEKpost.dmek",
                    "DSAEKpost.dsaek", "DSAEKpost.dsaek", "post.penetrating.keratoplasty",
                    "DSAEKpost.kt", "post.kt", "DSAEK.POST.PKP", "surgery.post.dsaek",
                    "surgery.post.dmek", "surgery.post.pkp")) %>%
  # updateColnames("DMEK.post.dmek", NULL, 
  #                paste("signifie que cette greffe dmek a été réalisée",
  #                      "secondairement après une première greffe dmek",
  #                      "qui n'a pas réussie")) %>%
  deletingColnames(c("DMEK.post.dmek", "DSAEKpost.dmek", "DSAEKpost.dmek",
                     "DSAEKpost.dsaek", "DSAEKpost.dsaek", "post.penetrating.keratoplasty",
                     "DSAEKpost.kt", "post.kt", "DSAEK.POST.PKP", "surgery.post.dsaek",
                     "surgery.post.dmek", "surgery.post.pkp"))
# updateColnames("DSAEKpost.dmek") %>%
# updateColnames("DSAEKpost.dsaek") %>%
# updateColnames("DSAEKpost.kt") %>%
# updateColnames("post.kt") %>%
# select(-one_of("post.kt")) %>%
# updateColnames("post.penetrating.keratoplasty")

catCategory("Endothelial densities:")  

listeTableaux = listeTableaux %>%
  updateColnames("ECD.preop", c("preoperative.endothelial.cell.density",
                                "endothelial.density.of.the.graft",
                                "graft.endothelial.density..cell.mm2",
                                "graft.endothelial.density..cell.mm2.",
                                "graft.endothelial.density..cell.mm².",
                                "GRAFT.ECD",
                                "preoperative.ECD")) %>%
  updateColnames("ECD_D8", c("ECD.D8")) %>%
  updateColnames("ECD_D15", c("ECD.15D")) %>%
  updateColnames("ECD_M1", c("ECD.1M", "ECDm1")) %>%
  updateColnames("ECD_M2", c("ECD.2M")) %>%
  updateColnames("ECD_M3", c("ECD.3M", "ECDm3")) %>%
  updateColnames("ECD_M6", c("Endothelial.Density.6M",
                             "endothelial.cell.density.m6",
                             "endothelial.densitym6",
                             "Endothelial.density..6M",
                             "ECD.6M", "ECDm6")) %>%
  updateColnames("ECD_Y1", c("Endothelial.Density.12M",
                             "endothelial.cell.density12M",
                             "endothelial.density12m",
                             "ECD.12M")) %>%
  updateColnames("ECD_Y2", c("Endothelial.Density.24M",
                             "endothelial.cell.density.24.M",
                             "endothelial.density24m",
                             "ECD.24M")) %>%
  updateColnames("ECD_Y3", c("Endothelial.Density.36M",
                             "endothelial.cell.density.36.M",
                             "endothelial.density36m",
                             "ECD.36M")) %>%
  updateColnames("ECD_Y4", c("Endothelial.Density.48M",
                             "endothelial.cell.density.48.M",
                             "endothelial.density48m",
                             "ECD.48M")) %>%
  updateColnames("ECD_Y5", c("ECD.5Y"))

catCategory("Visual acuities in logMAR scale (not used directly in the PCA):") 

listeTableaux = listeTableaux %>%
  updateColnames("preoperative.VA", c("preoperative.Visual.Acuity",
                                      "preoperative.Visual.Acuity..logmar",
                                      "logmar.preop.va",
                                      "preop.logmar",
                                      "preoperative.VA")) %>%
  deletingColnames("av.pre.op") %>%
  updateColnames("VA_logD8", c("VAlogj8", "VAlog8j", "log8j", "VA.logj8", "VAlogD8")) %>%
  updateColnames("VA_logD15", c("VAlogj15", "VAlog15j", "log15j", "VA.logj15", "VAlogD15")) %>%
  updateColnames("VA_logM1", c("VAlog1m", "VAlog1M", "log1m", "VA.log1m", "VAlogM1")) %>%
  updateColnames("VA_logM3", c("VAlog3m", "VAlog3M", "log3m", "VA.log3m", "VAlogM3")) %>%
  updateColnames("VA_logM6", c("VAlog6m", "VAlog6M", "VAlogM6", "log6m", "VAlogM6")) %>%
  updateColnames("VA_logM12", c("VAlog12M", "VAlog1a", "VAlog1Y", "log1a", "VAlogM12")) %>%
  updateColnames("VA_logM24", c("VAlog24M", "VAlog2a", "log2a", "VAlog2Y", "VAlogM24"))

catCategory("Visual acuities in decimal scale:")  

listeTableaux = listeTableaux %>%
  updateColnamesVA("VA_preop", "preoperative.VA") %>%
  updateColnamesVA("VA_D8", "VA_logD8") %>%
  updateColnamesVA("VA_D15", "VA_logD15") %>%
  updateColnamesVA("VA_M1", "VA_logM1") %>%
  updateColnamesVA("VA_M3", "VA_logM3") %>%
  updateColnamesVA("VA_M6", "VA_logM6") %>%
  updateColnamesVA("VA_M12", "VA_logM12") %>%
  updateColnamesVA("VA_M24", "VA_logM24")

catCategory("Graft thicknesses:")

listeTableaux = listeTableaux %>%
  updateColnames("preoperative DSAEK CGT", "graft.s.thickness") %>%
  updateColnames("DSAEK CGT_D8", c("graft.thichkness8D","graft.thickness8D")) %>%
  updateColnames("DSAEK CGT_D15", c("graft.thickness15D","graft.thikness15D")) %>%
  updateColnames("DSAEK CGT_M1", c("graft.thickness1.M","graft.thickness1M")) %>%
  updateColnames("DSAEK CGT_M3", c("graft.thickness.3.M","graft.thickness3M")) %>%
  updateColnames("DSAEK CGT_M6", c("graft.thickness.6.M","graft.thickness6M")) %>%
  updateColnames("DSAEK CGT_M12", c("graft.thickness12M")) %>%
  updateColnames("DSAEK CGT_M24", c("graft.thickness24M"))
# old name : CGT_preop


catCategory("Graft pachymetry:")

listeTableaux = listeTableaux %>%
  updateColnames("DSAEK-CCT", "graft.s.central.pachymetry.greffon") %>%
  deletingColnames("post.cutting.graft.pachymetry") %>%
  updateColnames("pachy_preop", "PREOPERATIVE.PACHYMETRY") %>%
  updateColnames("pachy_after_cut", "graft.pachymetry..after.cutting") %>%
  updateColnames("pachy_D8", c("PACHY.D8", "graft.pachy.8D")) %>%
  updateColnames("pachy_D15", c("PACHY.D15", "GRAFT.PACHY.D15")) %>%
  updateColnames("pachy_M1", c("PACHY.M1", "GRAFT.PACHY.1M")) %>%
  updateColnames("pachy_M2", c("PACHYM2")) %>%
  updateColnames("pachy_M3", c("PACHY.M3", "GRAFT.PACHY.3M")) %>%
  updateColnames("pachy_M6", c("PACHY.M6", "GRAFT.PACHY.6M")) %>%
  updateColnames("pachy_Y1", c("PACHY.M12", "GRAFT.PACHY.12M")) %>%
  updateColnames("pachy_Y2", c("PACHY.24M", "GRAFT.PACHY.24M")) %>%
  deletingColnames("graft.pachymétry")


catCategory("Other variables:")  

listeTableaux = listeTableaux %>%
  updateColnames("FECD","fuchs.endothelial.corneal.dystrophy") %>%
  updateColnames("PBK",c("pseudophaquic.bullous.keratopathyKBP",
                         "pseudophaquic.bullous.keratopathy",
                         "PKB")) %>%
  updateColnames("Triple.DMEK","phacodmek..dmek.cataract.surgery.") %>%
  updateColnames("CME",c("cystoid.macular.edema.CME",
                         "Cystoide.Macular.Edema.EMC")) %>%
  updateColnames("kvirale", c("viralendothelila..keratopathy",
                              "VIRAL.KERATOPATHY")) %>%
  updateColnames("IrvingGass", c("IrVin.GASS.syndrome..Cystoid.Macular.Edema.",
                                 "irvine.gass.syndrom..EMC.",
                                 "irvine.gass.syndrom.equivalent.to.CME",
                                 "IrVin.GASS.syndrom",
                                 "IRVIN.GASS.SYFROM"))

```


```{r merging the data frames, results="asis"}

totColnames = c()
for (iTableau in 1:length(listeTableaux)){
  totColnames = c(totColnames, colnames(listeTableaux[[iTableau]]))
}
totColnames = sort(unique(totColnames))

# Merging the data frames
totalData.frame = c()
for (iTableau in 1:length(listeTableaux))
{
  colnames_loc = colnames( listeTableaux[[iTableau]] )
  colnamesToReplace = totColnames[which(! (totColnames %in% colnames_loc))]
  listeTableaux[[iTableau]][, colnamesToReplace] = NA
  
  totalData.frame = rbind(totalData.frame, listeTableaux[[iTableau]])
}
# totalData.frame$graft.age = as.numeric(totalData.frame$graft.age)
# Removing empty column graft.rejection
totalData.frame = totalData.frame[, - which(totColnames == "graft.rejection")] 

# # Remove redundant columns
# toRemove = c("IrVin.GASS.syndrome..Cystoid.Macular.Edema.", 
#              "irvine.gass.syndrom..EMC.",
#              "irvine.gass.syndrom.equivalent.to.CME")
# if (any(toRemove %in% colnames(totalData.frame))){
#   totalData.frame = totalData.frame[, - which(colnames(totalData.frame) %in% toRemove)]
# }

# Creation of indicator variables
cat("* Group of observations:\n")
if (params$includeDMEK){
  totalData.frame$is.dmek = as.numeric(totalData.frame$method == "dmek")
  cat("  + *is.dmek* = 1 if the observations belongs to the dmek group, else 0\n")
}
if (params$includeDSAEK){
  totalData.frame$is.dsaek = as.numeric(totalData.frame$method == "dsaek")
  cat("  + *is.dsaek*  = 1 if the observations belongs to the dsaek group, else 0\n")
}
if (params$includeUT_DSAEK){
  totalData.frame$is.ut_dsaek = as.numeric(totalData.frame$method == "ut_dsaek")
  cat("  + *is.ut_dsaek_preop* = 1 if the observations belongs to the ut_dsaek group, else 0\n")
}

vec_methods = totalData.frame[ , "method"]

totColnames = colnames(totalData.frame)
```


```{r computation cor matrix}
toRemove = which( totColnames %in% c(
  "method", "preoperative.VA", "VA_logD8"  ,
  "VA_logD15" , "VA_logM1"  , "VA_logM3"  ,
  "VA_logM6"  , "VA_logM12" , "VA_logM24" ))

X = as.matrix(totalData.frame[, - toRemove])
# Removing unnecessary columns
Xnorm = matrix(nrow = nrow(X), ncol = ncol(X))
for (j in 1:ncol(X)){
  Xnorm[, j] = (X[, j] - mean(X[, j], na.rm = TRUE)) / sd(X[, j], na.rm = TRUE)
}

cor_matrix = cor(x = X, use = "pairwise.complete.obs")

for (i in 1:ncol(X)) {
  for (j in 1:ncol(X)) {
    if(is.na(cor_matrix[i,j])) {
      cor_matrix[i,j] = 0
    }
  }
}

for (i in 1:nrow(X)) {
  for (j in 1:ncol(X)) {
    if (is.na(Xnorm[i,j])){
      Xnorm[i,j] = 0
    }
  }
}
```


```{r names special variables}
# variablesCGT =
#   c("preoperative DSAEK CGT" , "DSAEK CGT_D8" , "DSAEK CGT_D15" , "DSAEK CGT_M1" ,
#     "DSAEK CGT_M3" , "DSAEK CGT_M6", "DSAEK CGT_M12" , "DSAEK CGT_M24" )

variablesVA = 
  c("VA_preop", "VA_D8", "VA_D15", "VA_M1", "VA_M3",
    "VA_M6", "VA_M12", "VA_M24")

variablesECD =
  c("ECD_preop", "ECD_D8", "ECD_D15", "ECD_M1", "ECD_M2", "ECD_M3",
    "ECD_M6", "ECD_Y1", "ECD_Y2", "ECD_Y3", "ECD_Y4")

variablesPACHY =
  c("pachy_preop", "pachy_after_cut", "pachy_D8", "pachy_M1", "pachy_M2", "pachy_M3",
    "pachy_M6", "pachy_Y1", "pachy_Y2")

getModifNorm <- function(X, variablesToBeChanged){
  whereVariables = colnames(X) %in% variablesToBeChanged
  if (length(which(whereVariables)) == 0){
    stop(whereVariables, "not present in the matrix X.")
  }
  modifNorm = (1/sqrt(length(which(whereVariables)))) * as.numeric(whereVariables) +
    1 * (as.numeric(!whereVariables))
  
  return (modifNorm)
}

modifNormVA = getModifNorm(X, variablesVA)
modifNormECD = getModifNorm(X, variablesECD)
modifNormPACHY = getModifNorm(X, variablesPACHY)

# modifNormCGT = (1/sqrt(length(variablesCGT))) * as.numeric(colnames(X) %in% variablesCGT) +
#   1 * (as.numeric(!colnames(X) %in% variablesCGT))
# modifNormVA = (1/sqrt(length(variablesVA))) * as.numeric(colnames(X) %in% variablesVA) +
#   1 * (as.numeric(!colnames(X) %in% variablesVA))
# modifNormECD = (1/sqrt(length(variablesECD))) * as.numeric(colnames(X) %in% variablesECD) +
#   1 * (as.numeric(!colnames(X) %in% variablesECD))

# Normalization of the following pairs:
# MAN/WOMAN, right.eye/left.eye, locoregional.anaesthesia/general.anaesthesia
variablesPairs = c("MAN", "WOMAN", "right.eye", "left.eye",
                   "locoregional.anaesthesia", "general.anaesthesia",
                   "failure", "success")
modifNormAll = (1/sqrt(2)) * as.numeric(colnames(X) %in% variablesPairs) +
  1 * (as.numeric(!colnames(X) %in% variablesPairs))
cor_matrix = diag(modifNormAll) %*% cor_matrix %*% diag(modifNormAll)
```


```{r function for PCA}

my_PCA <- function(cormat)
{
  # 1- Diagonalization
  res_pca = eigen(cormat)
  
  # 2- Scree plot
  plot_scree = ggplot(data=NULL,
                      aes(x=1:length(res_pca$values),
                          y=res_pca$values/sum(res_pca$values))) +
    # geom_point(size=2)+
    geom_col()+
    # labs(title="Scree plot of the scaled PCA") +
    xlab("Principal components") +
    ylab("Eigenvalue / Sum(eigenvalues)")
  
  # 3- Biplot 
  vecpropres_1 = res_pca$vectors[,1]
  vecpropres_2 = res_pca$vectors[,2]
  vecpropres_12 = cbind(vecpropres_1, vecpropres_2)
  obs_firstplane = Xnorm %*% vecpropres_12
  
  vecColors = c("dmek" = "brown", "dsaek" = "purple", 
                "ut_dsaek" = "blue")
  # vecSymb = c("dmek" = 1, "dsaek_M6" = 9, 
  #                "ut_dsaek_M6" = 7, "dsaek_preop" = 5, 
  #                "ut_dsaek_preop" = 22)
  vecSymb = c("dmek" = 19, "dsaek" = 9, "ut_dsaek" = 7)
  vecLabels = c("dmek" = "DMEK" ,
                "dsaek" = "thick grafts\n after DSAEK" ,
                "ut_dsaek" = "thin graftsn after DSAEK")
  
  PCA12 <- ggplot() + geom_point(aes(x = obs_firstplane[,1],
                                     y = obs_firstplane[,2],
                                     col = vec_methods,
                                     shape = vec_methods), size = 1.5) +
    scale_colour_manual(values = vecColors, name = "Method", 
                        labels = vecLabels) +
    scale_shape_manual(values = vecSymb, name = "Method", 
                       labels = vecLabels) +
    theme(text=element_text(size=14),
          axis.text = element_text(size=10) ) +
    theme(panel.grid.minor = element_line(size = 1)) +
    theme(legend.spacing.y = unit(0.01, "npc"),
          legend.text =
            element_text(margin = margin(3,0,3,0))) +
    xlab("PC1") + ylab("PC2")
  
  Cluster = vec_methods
  Cluster[which(vec_methods %in% c("dmek"))] = "DMEK"
  Cluster[which(vec_methods %in% c("dsaek"))] = "Thick DSAEK grafts"
  Cluster[which(vec_methods %in% c("ut_dsaek"))] = "Thin DSAEK grafts"
  
  PCA12_ellipses <- PCA12 +
    geom_mark_ellipse(aes(x = obs_firstplane[,1],
                          y = obs_firstplane[,2],
                          fill = Cluster, label = Cluster),
                      alpha = 0.1, show.legend = FALSE, expand = 0)
  # coord_cartesian(xlim = c(-10,7), ylim = c(-8,8))
  
  
  # 4- Correlation circle
  val_plus = res_pca$values * as.numeric(res_pca$values >= 0)
  
  cor.factors <- NULL
  for (j in 1:ncol(X)){
    rf <- sqrt(val_plus[j])*res_pca$vectors[,j]
    cor.factors <- cbind(cor.factors,rf)
  }
  rownames(cor.factors) <- colnames(X)
  colnames(cor.factors) <- paste("F",1:ncol(X),sep="")
  
  # 5- Factor loadings
  DataFrameLoadings = data.frame(
    Variable = factor(rep(colnames(X), times = 2),
                      levels = sort(colnames(X), decreasing = TRUE)),
    Loadings = c(cor.factors[,1], cor.factors[,2]),
    Factor = rep(c("PC1","PC2"), each = ncol(X))
  )
  PlotLoadings = ggplot(DataFrameLoadings) +
    geom_col(aes(x = Variable, y = Loadings)) +
    facet_grid(cols = vars(Factor)) +
    coord_flip()
  
  return( list(res_pca = res_pca, plot_scree = plot_scree, 
               PCA12_ellipses = PCA12_ellipses, cor.factors = cor.factors,
               PlotLoadings = PlotLoadings) )
}
```


```{r, echo=FALSE, results='asis', label="all PCAs"}
out = list()
listCorrMatrix = list()
listPCA = list()
for (i in 1:nrow(df_normalizations) ){
  cor_matrix_norm = cor_matrix
  if (df_normalizations$PACHY[i]){
    cor_matrix_norm = diag(modifNormPACHY) %*% cor_matrix_norm %*% diag(modifNormPACHY)
  }
  if (df_normalizations$BSCVA[i]){
    cor_matrix_norm = diag(modifNormVA) %*% cor_matrix_norm %*% diag(modifNormVA)
  }
  if (df_normalizations$ECD[i]){
    cor_matrix_norm = diag(modifNormECD) %*% cor_matrix_norm %*% diag(modifNormECD)
  }
  listCorrMatrix[[i]] = cor_matrix_norm
  listPCA[[i]] = my_PCA(cormat = listCorrMatrix[[i]])
  influence_PACHY = df_normalizations$PACHY_norm[i]
  influence_BSCVA = df_normalizations$BSCVA_norm[i]
  influence_ECD = df_normalizations$ECD_norm[i]
  
  nameAnalysis.long = paste("influence of PACHY ", influence_PACHY,
                            ", influence of BSCVA ", influence_BSCVA,
                            ", influence of ECD ", influence_ECD, sep = "")
  
  nameAnalysis.short = paste("PACHY ", influence_PACHY,
                             ", BSCVA ", influence_BSCVA,
                             ", ECD ", influence_ECD, sep = "")
  
  nameSection = paste("# PCA (", nameAnalysis.long, ") ", 
                      "{#s:", paste(
                        substring(influence_PACHY, 1, 1),
                        substring(influence_BSCVA, 1, 1),
                        substring(influence_ECD, 1, 1), sep = "-"),
                      "}", sep ="")
  
  # nameScreePlot = paste("'Scree plot -", nameAnalysis.short, "'")
  
  # out = c(out, knitr::knit_child('multiple-PCA-section.Rmd'))
  
  # cat(knitr::asis_output(knitr::knit_child("multiple-PCA-section.Rmd", quiet=TRUE)))
  result = knitr::knit_expand(file = "multiple-PCA-section.Rmd")
  out[[i]] = result
  
}
# knitr::knit(text = result,)
# paste(out, collapse='\n')
# cat(knitr::knit_child(text = paste(unlist(out),sep = "\n"), quiet = FALSE))
res <- lapply(out, function(x) {
  knitr::knit_child(
    text = x, envir = globalenv(), quiet = TRUE
  )
})
cat(unlist(res), sep = '\n')
```


