---
params:
  sizeCut: 130
  includeDMEK: TRUE
  includeDSAEK: TRUE
  includeUT_DSAEK: TRUE
  
title: "Univariate analysis for UDD paper"
author: "Alexis Derumigny"
date: "`r Sys.Date()`"

output: 
  bookdown::word_document2:
    toc: true
    fig_caption: true

knit: |
  (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(input), '-', Sys.Date(), '.docx'
      ),
      envir = globalenv()
    )
  })
---

<!-- The knit command modifies the output file to add automatically the date. -->
<!-- see https://bookdown.org/yihui/rmarkdown-cookbook/custom-knit.html -->


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

# Loading packages
library(readxl)
library(tidyverse)
library(ggforce)
library(ade4)
library(adegraphics)

# Loading cleaning functions
myFolder = here::here()
source("functions_cleaning.R")
```


# Introduction

```{r, echo=FALSE, results='asis', label="preparing the data frame"}
result = knitr::knit_expand(file = "preparing_dataframe.Rmd")

if (interactive()){
  result_ = knitr::knit(
    text = result, envir = globalenv(), quiet = TRUE)
} else {
  result_ = knitr::knit_child(
    text = result, envir = globalenv(), quiet = TRUE)
}

cat(result_, sep = '\n')
```


# Univariate statistical analysis

```{r}
vecVariables = c("patient.age", "WOMEN", "right.eye", "axial.eye.length",
                 "average.keratometry", "k1", "k2",
                 "PBK", "FECD", "second.graft", "kvirale", "gaz.sf6",
                 "general.anaesthesia", "Triple.DMEK", "first.surgery",
                 "donor.age", "double.cut", "cutting.blade.thickness",
                 "graft.without.marking","graft.with.a.simple.marking",
                 "graft.with.double.marking", 
                 "surgery.duration", "IrvingGass", "graft.rejection",
                 "rebubbling", "X2nd.rebubbling", "graft.detachment",
                 "failure.primary", "success",
                 "preoperative.VA", "VA_logD8", "VA_logD15", 
                 "VA_logM1", "VA_logM3", "VA_logM6","VA_logM12", "VA_logM24",
                 "pachy_D15", "pachy_D8", "pachy_M1", "pachy_M2", "pachy_M3", 
                 "pachy_M6", "pachy_preop", "pachy_Y1", "pachy_Y2",
                 "ECD.preop", "ECD_D15", "ECD_D8", "ECD_M1", "ECD_M2", "ECD_M3", "ECD_M6", 
                 "ECD_Y1", "ECD_Y2", "ECD_Y3", "ECD_Y4", "ECD_Y5"
                 # , "preoperative CGT", "CGT_D8", "CGT_D15", "CGT_M1", "CGT_M3",
                 # "CGT_M6", "CGT_M12", "CGT_M24"
                 )

df.univ = data.frame(
  nameVariable = as.character(rep(NA, length(vecVariables))),
  is01variable = as.logical(rep(NA, length(vecVariables))),
  
  n_dmek = as.numeric(rep(NA, length(vecVariables))),
  mean_dmek = as.numeric(rep(NA, length(vecVariables))),
  sd_dmek = as.numeric(rep(NA, length(vecVariables))),
  N_dmek = as.numeric(rep(NA, length(vecVariables))),
  pct_dmek = as.numeric(rep(NA, length(vecVariables))),
  
  n_dsaek = as.numeric(rep(NA, length(vecVariables))),
  mean_dsaek = as.numeric(rep(NA, length(vecVariables))),
  sd_dsaek = as.numeric(rep(NA, length(vecVariables))),
  N_dsaek = as.numeric(rep(NA, length(vecVariables))),
  pct_dsaek = as.numeric(rep(NA, length(vecVariables))),
  
  n_ut_dsaek = as.numeric(rep(NA, length(vecVariables))),
  mean_ut_dsaek = as.numeric(rep(NA, length(vecVariables))),
  sd_ut_dsaek = as.numeric(rep(NA, length(vecVariables))),
  N_ut_dsaek = as.numeric(rep(NA, length(vecVariables))),
  pct_ut_dsaek = as.numeric(rep(NA, length(vecVariables))),
  
  pval_all = as.numeric(rep(NA, length(vecVariables))),
  pval_dsaek_utdsaek = as.numeric(length(vecVariables)),
  pval_dmek_vs_all = as.numeric(length(vecVariables))
)

for (iVariable in 1:length(vecVariables))
{
  df.univ$nameVariable[iVariable] <- nameVariable <- vecVariables[iVariable]
  
  is01variable = all.equal(sort(unique(totalData.frame[,nameVariable])) , c(0,1) )
  df.univ$is01variable[iVariable] = isTRUE(is01variable)
  
  df.univ$n_dmek[iVariable] = length(which(
    totalData.frame$is.dmek == 1 & is.finite(totalData.frame[, nameVariable])))
  
  df.univ$n_dsaek[iVariable] = length(which(
    totalData.frame$is.dsaek == 1 & is.finite(totalData.frame[, nameVariable])))
  
  df.univ$n_ut_dsaek[iVariable] = length(which(
    totalData.frame$is.ut_dsaek == 1 & is.finite(totalData.frame[, nameVariable])))
  
  
  if (isTRUE(is01variable)){
    try({
      observations = na.omit(totalData.frame[totalData.frame$is.dmek == 1, nameVariable])
      df.univ$N_dmek[iVariable] = length(which(observations == 1))
      df.univ$pct_dmek[iVariable] = 
        df.univ$N_dmek[iVariable] / df.univ$n_dmek[iVariable] * 100
      
      observations = na.omit(totalData.frame[totalData.frame$is.dsaek == 1, nameVariable])
      df.univ$N_dsaek[iVariable] = length(which(observations == 1))
      df.univ$pct_dsaek[iVariable] = 
        df.univ$N_dsaek[iVariable] / df.univ$n_dsaek[iVariable] * 100
      
      observations = na.omit(totalData.frame[totalData.frame$is.ut_dsaek == 1, nameVariable])
      df.univ$N_ut_dsaek[iVariable] = length(which(observations == 1))
      df.univ$pct_ut_dsaek[iVariable] = 
        df.univ$N_ut_dsaek[iVariable] / df.univ$n_ut_dsaek[iVariable] * 100
      
      # Testing
      
      firstVariable = totalData.frame[, nameVariable]
      tab = table(firstVariable, totalData.frame[,"method"])
      res = chisq.test(x = tab)
      df.univ$pval_all[iVariable] = res$p.value
      
      res = chisq.test(x = tab[,2:3])
      df.univ$pval_dsaek_utdsaek[iVariable] = res$p.value
      
      res = chisq.test(x = cbind(tab[,1], tab[,2]+tab[,3]))
      df.univ$pval_dmek_vs_all[iVariable] = res$p.value
    }, silent = TRUE)
  } else {
    try({
      observations = na.omit(totalData.frame[totalData.frame$is.dmek == 1, nameVariable])
      df.univ$mean_dmek[iVariable] = mean(observations)
      df.univ$sd_dmek[iVariable] = sd(observations)
      
      observations = na.omit(totalData.frame[totalData.frame$is.dsaek == 1, nameVariable])
      df.univ$mean_dsaek[iVariable] = mean(observations)
      df.univ$sd_dsaek[iVariable] = sd(observations)
      
      observations = na.omit(totalData.frame[totalData.frame$is.ut_dsaek == 1, nameVariable])
      df.univ$mean_ut_dsaek[iVariable] = mean(observations)
      df.univ$sd_ut_dsaek[iVariable] = sd(observations)
      
      # Testing
      
      reg1 = lm(totalData.frame[,nameVariable] ~ totalData.frame$method)
      res = anova(reg1)
      df.univ$pval_all[iVariable] = res$`Pr(>F)`[1]
      
      res = t.test(totalData.frame[totalData.frame$is.ut_dsaek == 1, nameVariable] , 
                   totalData.frame[totalData.frame$is.dsaek == 1, nameVariable])
      df.univ$pval_dsaek_utdsaek[iVariable] = res$p.value
      
      res = t.test(totalData.frame[totalData.frame$is.dmek == 1, nameVariable] , 
                   totalData.frame[totalData.frame$is.dmek == 0, nameVariable])
      df.univ$pval_dmek_vs_all[iVariable] = res$p.value
    }, silent = TRUE)
  } 
}

df.univ$pval_dsaek_utdsaek[which(df.univ$pval_dsaek_utdsaek > 1)] <- NA
df.univ$pval_dsaek_utdsaek[which(!is.finite(df.univ$pval_dsaek_utdsaek))] <- NA

df.univ$pval_dmek_vs_all[which(df.univ$pval_dmek_vs_all > 1)] <- NA
df.univ$pval_dmek_vs_all[which(!is.finite(df.univ$pval_dmek_vs_all))] <- NA

df.univ$pval_all[which(df.univ$pval_all > 1)] <- NA
df.univ$pval_all[which(!is.finite(df.univ$pval_all))] <- NA

rm(is01variable)
```


```{r}
df.univ %>%
  mutate(
    mean_sd_dmek = paste0(formatC(mean_dmek, digits = 4, format = "fg"), "±",
                          formatC(sd_dmek, digits = 4, format = "fg")),
    N_pct_dmek = paste0(N_dmek, " (",
                        formatC(pct_dmek, digits = 1, format = "f"), ")"),
    dmek = if_else(is01variable, N_pct_dmek, mean_sd_dmek),
    
    mean_sd_dsaek = paste0(formatC(mean_dsaek, digits = 4, format = "fg"), "±",
                           formatC(sd_dsaek, digits = 4, format = "fg")),
    N_pct_dsaek = paste0(N_dsaek, " (",
                         formatC(pct_dsaek, digits = 1, format = "f"), ")"),
    dsaek = if_else(is01variable, N_pct_dsaek, mean_sd_dsaek),
    
    mean_sd_ut_dsaek = paste0(formatC(mean_ut_dsaek, digits = 4, format = "fg"), "±",
                              formatC(sd_ut_dsaek, digits = 4, format = "fg")),
    N_pct_ut_dsaek = paste0(N_ut_dsaek, " (",
                            formatC(pct_ut_dsaek, digits = 1, format = "f"), ")"),
    ut_dsaek = if_else(is01variable, N_pct_ut_dsaek, mean_sd_ut_dsaek)
  ) %>%
  dplyr::select(nameVariable, n_dmek, dmek, n_dsaek, dsaek, n_ut_dsaek, ut_dsaek,
                pval_all, pval_dsaek_utdsaek, pval_dmek_vs_all) %>%
  gt::gt(
    rowname_col = "nameVariable"
  ) %>%
  gt::fmt_number(
    columns = pval_all,
    rows = pval_all >= 0.001,
    n_sigfig = 4
  ) %>%
  gt::fmt_scientific(
    columns = pval_all,
    rows = pval_all < 0.001,
    n_sigfig = 4
  ) %>%
  gt::fmt_number(
    columns = pval_dsaek_utdsaek,
    rows = pval_dsaek_utdsaek >= 0.001,
    n_sigfig = 4
  ) %>%
  gt::fmt_scientific(
    columns = pval_dsaek_utdsaek,
    rows = pval_dsaek_utdsaek < 0.001,
    n_sigfig = 4
  ) %>%
  gt::fmt_number(
    columns = pval_dmek_vs_all,
    rows = pval_dmek_vs_all >= 0.001,
    n_sigfig = 4
  ) %>%
  gt::fmt_scientific(
    columns = pval_dmek_vs_all,
    rows = pval_dmek_vs_all < 0.001,
    n_sigfig = 4
  )
```


